### ISSUE TITLE
API doc update

### ISSUE THREAD

**Issue by xingweitian** [new-airbnb/soy-sauce#10]
@lyuboxin Please check it. I update "check_login" and "logout" in it.

[API doc](https://next.stoplight.io/birana/soy-sauce/version%2F1.0/soy-sauce%20back-end.oas2.yml?view=/reference/user-check-login/getuserchecklogin)

**Comment by lyuboxin** [comment]
Noted and thanks

Weitian Xing <notifications@github.com> 于2019年2月12日周二 下午1:06写道：

**Comment by xingweitian** [comment]
If there are no more questions here, you may want to kindly close this issue.
