### ISSUE TITLE
Check the CORS policy

### ISSUE THREAD

**Issue by lyuboxin** [new-airbnb/soy-sauce#20]
I came across an error when I sent a request to backend. The error is access to XMLHttpRequest at 'https://soy-sauce.herokuapp.com/user/register' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by xingweitian** [comment]
Thx, we will check it.

**Comment by xingweitian** [comment]
@lyuboxin Please test our APIs again, we have updated the CORS policy.

**Comment by lyuboxin** [comment]
@xingweitian Ok, I will test them now

**Comment by xingweitian** [comment]
This issue is closed because of resolving the CORS problem.
