### ISSUE TITLE
[bug] email duplication detection fails for signup

### ISSUE THREAD

**Issue by zhangjiangqige** [new-airbnb/soy-sauce#33]
**Describe the bug**
When signing up, using the same email with different passwords successes, which it shouldn't.

**To Reproduce**
1. Sign up with an email
2. Sign up again with that same email but with a different password

**Expected behavior**
The second sign up should fail due to duplicated email.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhangjiangqige** [comment]
This issue can be assigned to @lyuboxin and @ericqiangguo for practice.

**Comment by xingweitian** [comment]
Hint: Password and Email

**Comment by xingweitian** [comment]
I will fix it in Sunday, if you guys @lyuboxin @ericqiangguo  want to try it, please check this bug before Sunday.
