### ISSUE TITLE
Write API doc

### ISSUE THREAD

**Issue by zhangjiangqige** [new-airbnb/soy-sauce#5]
of login and signup, using Swagger

**Comment by xingweitian** [comment]
The API document url is here: [API Documentation](https://next.stoplight.io/birana/soy-sauce/version%2F1.0/soy-sauce%20back-end.oas2.yml?view=%2F)

Please check it and close this issue #5.

**Comment by zhangjiangqige** [comment]
@xingweitian is it possible that this website read the source file of the doc from this repo (so we can put the doc into version control)?

**Comment by xingweitian** [comment]
After discussion, we decide to keep using stoplight to maintain our API documentation for now.
