### ISSUE TITLE
Remove garbage data from mlab

### ISSUE THREAD

**Issue by xingweitian** [new-airbnb/soy-sauce#85]
Remember do it before Sunday. Also, add some real world data into our database.

**Comment by lyuboxin** [comment]
I will fix it

**Comment by xingweitian** [comment]
Please wait for me until I removed all the garbage data, and then you can add some good data.

**Comment by xingweitian** [comment]
I have already cleaned the database, @lyuboxin you can add some good data into it from now.

**Comment by xingweitian** [comment]
This issue is closed since it has been done.
